bashCopy code
- name: Generate kover coverage report
      run: ./gradlew koverXmlReportDebug

    - name: Add coverage report to PR
      uses: mi-kas/kover-report@v1.9
      with:
        path: app/build/reports/kover/reportDebug.xml
        title: Code Coverage
        update-comment: true
        min-coverage-overall: 32
        min-coverage-changed-files: 80
